"""Add like relation to comment

Revision ID: 57446893d08e
Revises: e1f88280833a
Create Date: 2023-11-17 21:45:50.099999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57446893d08e'
down_revision = 'e1f88280833a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=True))
        batch_op.drop_column('likes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), nullable=True))
        batch_op.drop_column('like_count')

    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_likes')
    )
    # ### end Alembic commands ###
