"""Add password hashing

Revision ID: c83004cae4ed
Revises: 1bace458a0d3
Create Date: 2023-11-27 10:30:45.797766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83004cae4ed'
down_revision = '1bace458a0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=75), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=75), nullable=True))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
