"""add user input to followers table

Revision ID: d81686887e68
Revises: 1b20dd78d57a
Create Date: 2023-11-18 00:36:41.628929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81686887e68'
down_revision = '1b20dd78d57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_friend', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_column('close_friend')

    # ### end Alembic commands ###
